lldpd: fix using uninitialized value
intel/openlldp pull request #102
Opened 2024-07-03 09:41 UTC by liuhangbin

When the length is less than sizeof(cmd.ifname), the cmd.ifname will be printed uninitialized, which could cause information leakage. Fix this by copying the maximum size of ifname before printing it out.

This issue was found through static code analysis.

Fixes: a37b7e0f3b66 ("lldpad: initial git commit")
Fixes: 3b559d8d0b52 ("VDP: vdptool first version")

2024-07-04 00:07 UTC, penguin359 requested changes
I don't think the memcpy is the correct fix here as it's shorter than what's in len. Instead, the printf() should probably be changed to print the source value from the memcpy for debug purposes. If the destination is printed, like now, the length parameter should be changed to match sizeof()-1.

2024-07-04 03:26 UTC, liuhangbin commented
> Instead, the printf() should probably be changed to print the source value from the memcpy for debug purposes

Thanks, the patch updated.

2024-07-06 07:27 UTC, penguin359 approved these changes
This looks good to me and fixes a read from an uninitialized value.

2024-07-10 14:09 UTC, apconole commented
Merged - thanks!

2024-07-10 14:09 UTC, closed without merging